### PR TITLE
ITPL-15498: serve-static version bump

### PR DESCRIPTION
**Pull request by CExWHamdan**

### CODE REVIEW

**Comment by literallynotjesus** [comment]
could be wrong, but iirc we don't use this part of the seneca-web api. it might be better to remove the dependency altogether.

**Comment by CExWHamdan** [comment]
> could be wrong, but iirc we don't use this part of the seneca-web api. it might be better to remove the dependency altogether.

This release will be used inside of our seneca fork itself to fix the vulnerability. The seneca-web we use in the app is a fork of 0.1.3 I believe while the one that seneca uses is at 0.3.3.

**Comment by literallynotjesus** [comment]
I took a look and its used to serve stuff like [angular](https://github.com/i-Sight/seneca-web/blob/bd1a10698f20d6cdbd41ac67ba282490ebd971b0/web.js#L433). It should definitively be removed in my opinion. Fewer dependencies mean fewer chances of future CVEs.

**Comment by CExWHamdan** [comment]
> I took a look and its used to serve stuff like [angular](https://github.com/i-Sight/seneca-web/blob/bd1a10698f20d6cdbd41ac67ba282490ebd971b0/web.js#L433). It should definitively be removed in my opinion. Fewer dependencies mean fewer chances of future CVEs.

Are you also suggesting removing its usage too from the code? Like in here: https://github.com/i-Sight/seneca-web/blob/bd1a10698f20d6cdbd41ac67ba282490ebd971b0/web.js#L433

**Comment by literallynotjesus** [comment]
Yea, its dead code as far as I can tell.

**Comment by CExWHamdan** [comment]
> Yea, its dead code as far as I can tell.

Hmm I think keeping the module and upgrading it sounds less risky than cleaning up the dead code. Like you, I'm not 100% sure the code is dead or what impact it could have removing it.

**Comment by literallynotjesus** [comment]
I think there's a misunderstanding - I'm personally certain that its not being used, but I welcome any corrections.

**Comment by CExWHamdan** [comment]
> I think there's a misunderstanding - I'm personally certain that its not being used, but I welcome any corrections.

Alright in this case I'll remove the code and let the tests validate the changes.

**Review by literallynotjesus — APPROVED** [review]
LGTM

**Pull request merged**
